services:
  pgdatabase:
    image: postgres:13 # docker image
    environment: # give names
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes: # mount volume
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports: # define port
      - "5432:5432"
  pgadmin: # image for pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "9090:80"
    